import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Header from './components/Header';
import Button from '../../shared/components/Button';
import { ErrorNotification, SuccessNotification } from '../../shared/components/ErrorNotification';
import useModel from './hooks/useModel';
import { playAlertSound } from '../../shared/constants/alertSounds';
export const Config = () => {
    const { config, isLoading, error, successMessage, updateConfig, handleUpdateConfig, setError, setSuccessMessage } = useModel();
    console.log('Config na página de configuração:', config);
    return (_jsxs("div", { className: "flex flex-col w-screen h-screen rounded-[8px] overflow-hidden bg-gray-900 backdrop-blur-sm border border-gray-600 ", children: [_jsx(Header, {}), _jsx(ErrorNotification, { error: error, onClose: () => setError(null) }), _jsx(SuccessNotification, { message: successMessage, onClose: () => setSuccessMessage(null) }), _jsxs("form", { action: "", className: "flex flex-col overflow-y-auto gap-6 px-6 py-6 scroll", onSubmit: handleUpdateConfig, children: [_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-white font-medium text-sm", htmlFor: "channel", children: "Nome do canal da Twitch" }), _jsx("input", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "channel", type: "text", value: config?.twitch.channel ?? '', placeholder: "Digite o nome do canal ex: devrogerinho", onChange: ({ target }) => updateConfig('twitch', { channel: target.value }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-white font-medium text-sm", htmlFor: "kick-channel", children: "Nome do canal da Kick" }), _jsx("input", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "kick-channel", type: "text", value: config?.kick.slug ?? '', placeholder: "Digite o nome do canal ex: devrogerinho", onChange: ({ target }) => updateConfig('kick', { slug: target.value }) })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-white font-medium text-sm", htmlFor: "youtube-channel", children: "Nome do canal do YouTube" }), _jsx("input", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "youtube-channel", type: "text", value: config?.youtube?.channelName ?? '', placeholder: "Ex: @OC\u00F3digodoRogerinho", onChange: ({ target }) => updateConfig('youtube', {
                                    channelName: target.value
                                }) })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("h3", { className: "text-white font-medium text-lg", children: "Mensagens e Alertas" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("label", { className: "text-white font-medium text-sm", htmlFor: "message-duration", children: ["Tempo de exibi\u00E7\u00E3o das mensagens:", ' ', (config?.messageDuration ?? 0) === 0
                                                ? 'Sempre visível'
                                                : `${config?.messageDuration} segundos`] }), _jsxs("select", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "message-duration", value: config?.messageDuration ?? 0, onChange: ({ target }) => updateConfig('messageDuration', parseInt(target.value)), children: [_jsx("option", { value: 0, children: "Sempre vis\u00EDvel" }), _jsx("option", { value: 5, children: "5 segundos" }), _jsx("option", { value: 10, children: "10 segundos" }), _jsx("option", { value: 15, children: "15 segundos" }), _jsx("option", { value: 30, children: "30 segundos" }), _jsx("option", { value: 60, children: "1 minuto" }), _jsx("option", { value: 120, children: "2 minutos" }), _jsx("option", { value: 300, children: "5 minutos" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "text-white font-medium text-sm", htmlFor: "alert-sound", children: "Som de alerta para novas mensagens" }), _jsxs("div", { className: "flex gap-2", children: [_jsxs("select", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "alert-sound", value: config?.alertSound ?? 'none', onChange: ({ target }) => updateConfig('alertSound', target.value), children: [_jsx("option", { value: "none", children: "Sem som" }), _jsx("option", { value: "alert1", children: "Alerta 1" }), _jsx("option", { value: "alert2", children: "Alerta 2" })] }), _jsx(Button, { className: "w-fit whitespace-nowrap", variant: "secondary", type: "button", disabled: (config?.alertSound ?? 'none') === 'none', onClick: () => playAlertSound(config?.alertSound), children: "Testar" })] })] })] }), _jsxs("div", { className: "space-y-4", children: [_jsx("h3", { className: "text-white font-medium text-lg", children: "Configura\u00E7\u00F5es de Fonte" }), _jsxs("div", { className: "flex flex-col space-y-2", children: [_jsxs("label", { className: "text-white font-medium text-sm", htmlFor: "font-size", children: ["Tamanho da fonte: ", config?.font?.size ?? 14, "px"] }), _jsx("input", { className: " h-2 bg-red-700 rounded-lg appearance-none cursor-pointer slider", id: "font-size", type: "range", min: "10", max: "24", value: config?.font?.size ?? 14, onChange: ({ target }) => updateConfig('font', {
                                            weight: config?.font?.weight ?? 700,
                                            size: parseInt(target.value)
                                        }) }), _jsxs("div", { className: "flex justify-between text-xs text-gray-400", children: [_jsx("span", { children: "10px" }), _jsx("span", { children: "24px" })] })] }), _jsxs("div", { className: "space-y-2", children: [_jsxs("label", { className: "text-white font-medium text-sm", htmlFor: "font-weight", children: ["Espessura da fonte:", ' ', config?.font?.weight === 300
                                                ? 'Leve'
                                                : config?.font?.weight === 400
                                                    ? 'Normal'
                                                    : config?.font?.weight === 500
                                                        ? 'Médio'
                                                        : config?.font?.weight === 600
                                                            ? 'Semi-negrito'
                                                            : config?.font?.weight === 700
                                                                ? 'Negrito'
                                                                : 'Normal'] }), _jsxs("select", { className: "w-full px-3 py-2 bg-gray-800 border border-gray-700 rounded text-white focus:outline-none focus:ring-2 focus:ring-primary-500 focus:border-transparent transition-all duration-200", id: "font-weight", value: config?.font?.weight ?? 400, onChange: ({ target }) => updateConfig('font', {
                                            size: config?.font?.size ?? 16,
                                            weight: parseInt(target.value)
                                        }), children: [_jsx("option", { value: 300, children: "Leve (300)" }), _jsx("option", { value: 400, children: "Normal (400)" }), _jsx("option", { value: 500, children: "M\u00E9dio (500)" }), _jsx("option", { value: 600, children: "Semi-negrito (600)" }), _jsx("option", { value: 700, children: "Negrito (700)" })] })] })] }), _jsxs("div", { className: "flex gap-2 items-center justify-end", children: [_jsx(Button, { className: "w-fit", variant: "secondary", type: "button", onClick: () => window.electron.ipcRenderer.send('close-config'), children: "Cancelar" }), _jsx(Button, { className: "w-fit", type: "submit", disabled: isLoading, children: isLoading ? 'Salvando...' : 'Salvar' })] })] })] }));
};
